### ISSUE TITLE
Asset validation failed

### ISSUE THREAD

**Issue by tuanemdev** [tareksabry1337/TensorFlowLiteSwift#1]
Invalid Bundle. The bundle MyApp.app/Frameworks/TensorFlowLiteC.framework does not support the minimum OS Version specified in the Info.plist.

Invalid Bundle. The bundle MyApp.app/Frameworks/TensorFlowLiteCCoreML.framework does not support the minimum OS Version specified in the Info.plist.

**Comment by tareksabry1337** [comment]
That's Xcode 15.3 specific, Let me fix this over the weekend and I'll upload a new release

**Comment by tuanemdev** [comment]
thanks you for create TF with SPM and fix that issue

**Comment by tareksabry1337** [comment]
@tuanemdev This is now resolved, can you try to pull the latest once more?

**Comment by tareksabry1337** [comment]
I just verified this in the project I'm using and it's working as expected, closing this!
